-- 코드를 입력하세요
select ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
from ANIMAL_OUTS
where ANIMAL_OUTS.ANIMAL_ID not in (select ANIMAL_INS.ANIMAL_ID from ANIMAL_INS);



-- SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.name FROM ANIMAL_OUTS 
-- LEFT JOIN ANIMAL_INS 
-- ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
-- WHERE ANIMAL_INS.ANIMAL_ID IS NULL;
